#!/usr/bin/env python3
##
## EPITECH PROJECT, 2022
## 204
## File description:
## 204
##

import sys
from math import *
import numpy as np

def two(a,b,x):
        h = -(((x-a)**2)/(2*b**2))
        h = x-a
        h = h**2
        j = b**2
        j = 2*j
        h = (-h) /j
        return (h)

def one(a,b):
        h = 2 * pi
        h = sqrt(h)
        h = b * h
        h = 1 / h
        return (h)

if __name__ == "__main__":
        arg = len(sys.argv) - 1
        c = 0
        d = 201
        if (arg < 2 or arg > 4):
                print ("USAGE\n    ./205IQ u s [IQ1] [IQ2]\n\nDESCRIPTION\n    u       mean\n    s       standard deviation\n    IQ1     minimum IQ\n    IQ2     maximum IQ")
                if (arg != 1):
                        exit (84)
                if (sys.argv[1] == "-h"):
                        exit (0)
                else:
                        exit (84)
        for y in range(1, arg+1):
                for x in range(0, len(sys.argv[y])):
                    if ((sys.argv[y][x] < '0' or sys.argv[y][x] > '9') and sys.argv[y][x] != '.'):
                            print ("%s invalide argument"%sys.argv[y])
                            exit (84)
        a = float(sys.argv[1])
        b = float(sys.argv[2])
        if (a > 200 or a < 0):
                print ("%d not in range 0 and 200"%a)
                exit (84)
        if (b > 200 or b < 1):
                print ("%d not in range 1 and 200"%b)
                exit (84)
        if (arg >= 3):
                c = float(sys.argv[3])
                if (c > 200 or c < 0):
                        print ("%d not in range 0 and 200"%c)
                        exit (84)
        if (arg == 4):
                d = float(sys.argv[4])
                if (d > 200 or d < 0):
                        print ("%d not in range 0 and 200"%d)
                        exit (84)
        if (d < c):
                print ("maximum %d cannot be smaller than minimum %d"%(d,c))
                exit (84)
        if (arg == 2):
                for x in range (c, d):
                        p = one(a,b)*exp(two(a,b,x))
                        print ("%d %.5f"%(x,p))
        if (arg == 3):
                p = 0
                for x in np.arange (0, c, 0.01):
                        p = p + (one(a,b)*exp(two(a,b,x)))
                print ("%.1f%% of people have an IQ inferior to %d"%(p,c))
        if (arg == 4):
                p = 0
                for x in np.arange (c, d, 0.01):
                        p = p + (one(a,b)*exp(two(a,b,x)))
                print ("%.1f%% of people have an IQ between %d and %d"%(p,c,d))
        exit (0)
